# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-17 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_simple_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simplegallery',
            options={'verbose_name_plural': 'Simple Galleries'},
        ),
    ]
